version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - .:/app
    command: sh -c "npm rebuild esbuild && npm run server"